server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false