server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY
  zipkin:
    base-url: http://172.19.0.1:9411/



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false