version: "3.0"

services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  country-service:
    build:
      context: ./country-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"

  director-service:
    build:
      context: ./director-service
      dockerfile: Dockerfile
    ports:
      - "9004:9004"

  distribution-service:
    build:
      context: ./distribution-service
      dockerfile: Dockerfile
    ports:
      - "9005:9005"

  genre-service:
    build:
      context: ./genre-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9191:9191"

  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

#  jaeger:
#    environment:
#      - COLLECTOR_ZIPKIN_HOST_PORT=9411
#    image: jaegertracing/all-in-one
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14250:14250"
#      - "14268:14268"
#      - "14269:14269"
#      - "9411:9411"