server:
  port: 9002

spring:
  application:
    name: GENRE-SERVICE
  zipkin:
    base-url: http://172.19.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.19.0.1:8761/eureka/
  instance:
    hostname: 172.19.0.1