server:
  port: 9002

spring:
  application:
    name: GENRE-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
#    base-url: http://172.18.0.1:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://172.18.0.1:8761/eureka/
  instance:
    hostname: localhost
#    hostname: 172.18.0.1